------------------------------------------------------------------------------
-- Client Lua Script for DruseraBossMods
--
-- Copyright (C) 2015 Thierry carré
--
-- Player Name: 'Immé sama'
-- Guild Name: 'Les Solaris'
-- Server Name: Jabbit(EU)
------------------------------------------------------------------------------
------------------------------------------------------------------------------
--
--  TODO: Write a presentation.
--
------------------------------------------------------------------------------
require "Window"
require "GameLib"
require "Apollo"

------------------------------------------------------------------------------
-- Constants
------------------------------------------------------------------------------
local DRUSERABOSSMODS_VERSION =  "0.15-alpha" -- "@project-version@"
local DEFAULT_PROFILE = {
  profile = {
    DBM = {
      VERSION = DRUSERABOSSMODS_VERSION,

      --#####  Color Palette by Paletton.com
      --#####  Palette URL: http://paletton.com/#uid=23n0u0klllln3NPmctOkucSjC4p
      PRIMARY_COLORS = {
        --*** Primary colors:
        shade0 = "FF255C69",
        shade1 = "FF41BAD7",
        shade2 = "FF308093",
        shade3 = "FF18383F",
        shade4 = "FF091316",
      },
      COMPLEMENT_COLORS = {
        --*** Complement colors:
        shade0 = "FFAA7139",
        shade1 = "FFFFA347",
        shade2 = "FFED9B49",
        shade3 = "FF674525",
        shade4 = "FF23180E",
        --#####  Generated by Paletton.com (c) 2002-2014
      },
    },
    CUSTOM = {
      BAR = {
        THRESHOLD_N2H = 0,
        NORMAL = {
          SORT = Window.CodeEnumArrangeOrigin.LeftOrTop,
          FILL = false,
          DISPLAY_TIME = true,
          PROGRESS_SPRITE = "bar_default",
          FONT = "CRB_Interface11_BO",
        },
        HIGHLIGHT = {
          SORT = Window.CodeEnumArrangeOrigin.LeftOrTop,
          FILL = false,
          DISPLAY_TIME = true,
          PROGRESS_SPRITE = "bar_default",
          FONT = "CRB_Interface12_BO",
        },
      },
      HEALTH = {
        SORT = Window.CodeEnumArrangeOrigin.LeftOrTop,
        FILL = false,
        PROGRESS_SPRITE = "bar_default",
        FONT = "CRB_Interface11_BO",
      },
      CAST = {
        ENABLE = true,
      },
      MESSAGE = {
        ENABLE = true,
        HIGHLIGHT_WND_ENABLE = true,
        NORMAL = {
          SORT = Window.CodeEnumArrangeOrigin.LeftOrTop,
          FONT = "CRB_Interface11_BO",
        },
        HIGHLIGHT = {
          SORT = Window.CodeEnumArrangeOrigin.LeftOrTop,
          FONT = "CRB_Interface12_BO",
        },
      },
      SOUND = {
        ENABLE = true,
      },
      MARKER = {
        ENABLE = true,
      },
    },
  },
}

------------------------------------------------------------------------------
-- Initialization
------------------------------------------------------------------------------
local DruseraBossMods = {}

function DruseraBossMods:new(o)
  o = o or {}
  setmetatable(o, self)
  self.__index = self
  self.DRUSERABOSSMODS_VERSION = DRUSERABOSSMODS_VERSION
  self.DataBase = {}
  return o
end

function DruseraBossMods:Init()
  Apollo.RegisterAddon(self, false, "", {})
  self.L = Apollo.GetPackage("Gemini:Locale-1.0").tPackage:GetLocale("DruseraBossMods")
  self.db = Apollo.GetPackage("Gemini:DB-1.0").tPackage:New(self, DEFAULT_PROFILE)
end

function DruseraBossMods:OnDependencyError(strDep, strError)
  Print("OnDependencyError: " .. strDep .. "  " ..strError)
  return false
end

function DruseraBossMods:OnLoad()
  Apollo.LoadSprites("DruseraBossMods_Sprites.xml")
  self.xmlDoc = XmlDoc.CreateFromFile("DruseraBossMods.xml")
  self.xmlDoc:RegisterCallback("OnDocLoaded", self)
end

function DruseraBossMods:OnDocLoaded()
  if self.xmlDoc == nil or not self.xmlDoc:IsLoaded() then return end

  Apollo.RegisterEventHandler("WindowManagementReady", "OnWindowManagementReady", self)
  -- From highest layer to lowest layer.
  self:GUIInit()
  self:HUDInit()
  self.CombatManager = self:CombatManagerInit()
end

function DruseraBossMods:OnWindowManagementReady()
  self:GUIWindowsManagementAdd()
  self:HUDWindowsManagementAdd()
end

------------------------------------------------------------------------------
-- DruseraBossMods Instance
------------------------------------------------------------------------------
local DruseraBossModsInst = DruseraBossMods:new()
DruseraBossModsInst:Init()
-- For debugging purpose through GeminiConsole, quite useful.
_G["DBM"] = DruseraBossModsInst
